### ISSUE TITLE
SlidesSerializer falla cuando el modelo no tiene una :image asociada

### ISSUE THREAD

**Issue by JeremasPosta** [alkemyTech/OT112-Server#63]
# SlidesSerializer falla cuando el modelo no tiene una :image asociada

Habría que agregar el condicional a la clase `SlidesSerializer` en la parte de la imagen.

Que quede algo asi:

```
24    Rails.application.routes.url_helpers.rails_blob_path(slide.image, only_path: true) if slide.image.attached?
```
El archivo es:

[app/serializers/slides_serializer.rb](https://github.com/alkemyTech/OT112-Server/blob/5866a283e048d804f8e69c13fdc07d0a0d0ce259/app/serializers/slides_serializer.rb)

**Comment by JorgeGarciaMdz** [comment]
Error line 38. "Slide.Serializer...."
Editar los tipos de respuesta (no authorized, no found entity)
