### ISSUE TITLE
Errores en users_controller

### ISSUE THREAD

**Issue by JeremasPosta** [alkemyTech/OT112-Server#69]
# Errores en users_controller

@AleYanc  detecta error en linea 11 de `users_controller`.
@JorgeGarciaMdz  detecta error en linea 12 del mismo archivo.

```
10      render json: {
11        "status": "Only admin users can list announcements"
12      }, status: ::unauthorized
13    end
``` 

Archivo: [app/controllers/api/v1/users_controller.rb](https://github.com/alkemyTech/OT112-Server/blob/8e491f8c3b4c3d91baa456b7db4a26db3ceb7611/app/controllers/api/v1/users_controller.rb)

**Comment by AleYanc** [comment]
### Otra cosa
No hay un error handling correspondiente al `set_user` cuando el ID enviado a través de los parámetros no existe. 
Solución sugerida: 
```ruby
rescue ActiveRecord::RecordNotFound
    render json: {error: "Could not find user with ID '#{params[:id]}'"}, status: :unprocessable_entity
```
